"""Minimal web server for the Signal Tracker dashboard on Railway."""

import os
from pathlib import Path
from flask import Flask, send_file, abort, jsonify

app = Flask(__name__)

DASHBOARD = Path(__file__).parent / "reports" / "dashboard.html"


@app.route("/")
def index():
    if not DASHBOARD.exists():
        abort(404, "Dashboard not generated yet — run main.py first.")
    return send_file(str(DASHBOARD))


@app.route("/health")
def health():
    return {"status": "ok", "dashboard_exists": DASHBOARD.exists()}


@app.route("/api/weekly-stats")
def weekly_stats():
    """Return signal counts for the last 7 days. Generated by main.py and committed to git."""
    stats_json = Path(__file__).parent / "data" / "weekly-stats.json"
    if not stats_json.exists():
        return jsonify({"error": "weekly-stats.json not found — run main.py first"}), 503
    import json
    return jsonify(json.loads(stats_json.read_text()))


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    app.run(host="0.0.0.0", port=port)
